spring:
  h2:
    console:
      enabled: true
      settings:
        trace: true
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        type: trace
    database: h2
  datasource:
    url: jdbc:h2:file:./build/h2db/samp #DATABASE_TO_UPPER=FALSE;
    username: smp
    initialization-mode: embedded
    driver-class-name: org.h2.Driver
    platform: h2
